#include "item.h"

#include <iomanip>
#include <sstream>
#include <string>
using namespace std;

/*
 * Store the item fields exactly as entered/generated by the caller.
 */
Item::Item(const string &id, const string &name, int qty, double price, int thresh, const string &category)
    : itemId(id), name(name), quantity(qty), price(price), threshold(thresh), category(category) {}

/*
 * Read-only field accessors.
 */
const string &Item::getItemId() const
{
    return itemId;
}

const string &Item::getName() const
{
    return name;
}

int Item::getQuantity() const
{
    return quantity;
}

double Item::getPrice() const
{
    return price;
}

int Item::getThreshold() const
{
    return threshold;
}

const string &Item::getCategory() const
{
    return category;
}

/*
 * Mutators used by manager update flows.
 */

void Item::setName(const string &name)
{
    this->name = name;
}

void Item::setQuantity(int quantity)
{
    this->quantity = quantity;
}

void Item::setPrice(double price)
{
    this->price = price;
}

void Item::setThreshold(int threshold)
{
    this->threshold = threshold;
}

void Item::setCategory(const string &category)
{
    this->category = category;
}

/*
 * Low stock starts when quantity reaches the configured threshold.
 */
bool Item::isLowStock() const
{
    return quantity <= threshold;
}

/*
 * Format one inventory row for CLI display.
 */
string Item::toString() const
{
    ostringstream stream;
    stream << "ID: " << itemId << " | Name: " << name
           << " | Category: " << category
           << " | Qty: " << quantity
           << " | Price: $" << fixed << setprecision(2) << price
           << " | Threshold: " << threshold;
    return stream.str();
}